//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicom.DataProvider.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHYFModels : DbContext
    {
        public SHYFModels()
            : base("name=SHYFModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_DevAddr> T_DevAddr { get; set; }
        public virtual DbSet<T_Devs> T_Devs { get; set; }
        public virtual DbSet<T_ESDay> T_ESDay { get; set; }
        public virtual DbSet<T_ESHour> T_ESHour { get; set; }
        public virtual DbSet<T_ESMin> T_ESMin { get; set; }
        public virtual DbSet<T_Stage> T_Stage { get; set; }
        public virtual DbSet<T_Stats> T_Stats { get; set; }
    }
}
