//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicom.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Devs
    {
        public int Id { get; set; }
        public string DevCode { get; set; }
        public string StatId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime PreEndTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public byte DevStatus { get; set; }
        public string VideoURL { get; set; }
    }
}
