//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicom.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DevAddr
    {
        public int DevId { get; set; }
        public byte[] NodeId { get; set; }
    }
}
