//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicom.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Stage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Stage()
        {
            this.T_Stats = new HashSet<T_Stats>();
        }
    
        public byte Id { get; set; }
        public string StageName { get; set; }
    
        public virtual T_Stage T_Stage1 { get; set; }
        public virtual T_Stage T_Stage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Stats> T_Stats { get; set; }
    }
}
