//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicom.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Stats
    {
        public int Id { get; set; }
        public string StatCode { get; set; }
        public Nullable<int> StatCodeUp { get; set; }
        public string StatName { get; set; }
        public string ChargeMan { get; set; }
        public string Telepone { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public string Department { get; set; }
        public string Address { get; set; }
        public int Country { get; set; }
        public string Street { get; set; }
        public double Square { get; set; }
        public System.DateTime ProStartTime { get; set; }
        public byte Stage { get; set; }
        public string ProType { get; set; }
        public Nullable<int> AlarmType { get; set; }
    
        public virtual T_Stage T_Stage { get; set; }
    }
}
